/***************************************************************************
  This file was created by the program FALCO which is a module 
  of WinFACT (Windows Fuzzy And Control Tools).

  Instead of editing this file, modify FALCOs Source-File
  with FLOP and generate it once again.

  Generated by : Tobias Hupel
            on : TOBYS-NOTEBOOK
  FALCO Version: 8.0.0.9
  Source-File  : C:\Users\Tobias Hupel\Documents\Projects\MCU_Rally_2018\res\Car2018\Increased_Length\line_abs_9SI_V.fuz from:02/05/2018 15:57:04
  Timestamp    : 02/05/2018 15:57:13

  Description of the fuzzy controller implemented in this code:
  =============================================================

    Inputs: 2
     LinePosition
     Velocity

    Outputs: 1
     ServoAngleDeg

    Rules: 15

    Inferencemechanism: Max-Min
    Method of defuzzyfication: center of gravity (Intergration via 60 steps)
    Number format: 4 Byte IEEE float
***************************************************************************/

#ifndef line_abs_9SI_V_F4
#define line_abs_9SI_V_F4 line_abs_9SI_V_F4



#include "fuzzy_F4.h"

#ifdef __cplusplus
  extern "C" {
#endif

void line_abs_9SI_V_F4_SetNumType(void);

void line_abs_9SI_V_F4_init(void);

void line_abs_9SI_V_F4_calc(
       const NumTypeF4_t i0,
       const NumTypeF4_t i1,
       NumTypeF4_t *o0);

void line_abs_9SI_V_F4_free(void);
#ifdef __cplusplus
  }
#endif


#endif
