/***************************************************************************
  This file was created by the program FALCO which is a module 
  of WinFACT (Windows Fuzzy And Control Tools).

  Instead of editing this file, modify FALCOs Source-File
  with FLOP and generate it once again.

  Generated by : Tobias Hupel
            on : TOBYS-NOTEBOOK
  FALCO Version: 8.0.0.9
  Source-File  : C:\Users\Tobias Hupel\Documents\Projects\MCU_Rally_2018\res\Car2018\Increased_Length\target_speed.fuz from:02/05/2018 16:13:08
  Timestamp    : 02/05/2018 16:13:14

  Description of the fuzzy controller implemented in this code:
  =============================================================

    Inputs: 1
     LineDevAbs

    Outputs: 1
     Velocity

    Rules: 2

    Inferencemechanism: Max-Min
    Method of defuzzyfication: center of gravity (Intergration via 60 steps)
    Number format: 4 Byte IEEE float
***************************************************************************/

#include "target_speed_F4.h"

/*############################################################################*/
/*                        Sets of all input variables                         */
/*############################################################################*/

static const NumTypeF4Point_t target_speed_F4_LineDevAbs_0_Middle[4]={
   {0, 0},
   {0, 1},
   {1, 1},
   {1.5, 0}};
static const NumTypeF4Point_t target_speed_F4_LineDevAbs_1_Turn[4]={
   {1, 0},
   {1.5, 1},
   {3.5, 1},
   {3.5, 0}};

/*############################################################################*/
/*                        Sets of all output variables                        */
/*############################################################################*/

static const NumTypeF4Point_t target_speed_F4_Velocity_0_Turn[1]={
   {2, 1}};
static const NumTypeF4Point_t target_speed_F4_Velocity_1_Straight[1]={
   {2.20000004768, 1}};


static const FuzzySetF4_t target_speed_F4_LineDevAbs_0[2]={
   {4, target_speed_F4_LineDevAbs_0_Middle},
   {4, target_speed_F4_LineDevAbs_1_Turn}};
/*############################################################################*/
/*                              Input variables                               */
/*############################################################################*/

static const LinguisticInputVariableF4_t target_speed_F4_Input[1]={
   {2, target_speed_F4_LineDevAbs_0}};


static const FuzzySetF4_t target_speed_F4_Velocity_0[2]={
   {1, target_speed_F4_Velocity_0_Turn},
   {1, target_speed_F4_Velocity_1_Straight}};
/*############################################################################*/
/*                              Output variables                              */
/*############################################################################*/

static const LinguisticOutputVariableF4_t target_speed_F4_Output[1]={
   {2, target_speed_F4_Velocity_0, 0, 0}};
/*############################################################################*/
/*                         Premises of the rule base                          */
/*############################################################################*/

static const char target_speed_F4_RuleBase_pre[2*1]={
   1,
   2};

/*############################################################################*/
/*                        Conclusion of the rule base                         */
/*############################################################################*/

static const char target_speed_F4_RuleBase_con[2*1]={
   2,
   1};

/*############################################################################*/
/*                           Weighting of the rules                           */
/*############################################################################*/

static const NumTypeF4_t target_speed_F4_RuleBase_weight[2]={
   1,
   1};

/*############################################################################*/
/*                    All together in FuzzyControllerF4_t                     */
/*############################################################################*/
static const FuzzyControllerF4_t target_speed_F4_FC={
   1,
   1,
   2,
   target_speed_F4_Input,
   target_speed_F4_Output,
   target_speed_F4_RuleBase_pre,
   target_speed_F4_RuleBase_con,
   target_speed_F4_RuleBase_weight,
   MAX_MIN,
   DEFUZZY_COG,
   60,
   AND_MIN,
   OR_MAX};


/*############################################################################*/
/*                       Call this function to be sure                        */
/*                  to work with the correct number format.                   */
/*############################################################################*/


void target_speed_F4_SetNumType(void)
{
}


/*############################################################################*/
/*                           Structure of pointers                            */
/*           This structure is allocated in the xx_init() function            */
/*        and is needed for the calculation in the xx_calc() function.        */
/*############################################################################*/

static FCMemF4_t target_speed_F4_FCMem;


/*############################################################################*/
/*                          Initializiation function                          */
/*                  Call this function before the others !!                   */
/*############################################################################*/


void target_speed_F4_init(void)
{
  FCF4_init(&target_speed_F4_FC, &target_speed_F4_FCMem);
}
/*############################################################################*/
/*                    Function representing the controller                    */
/*############################################################################*/


void target_speed_F4_calc(
       const NumTypeF4_t i0,
       NumTypeF4_t *o0)
{
  NumTypeF4_t ai[1];
  NumTypeF4_t ao[1];
  ai[0]=i0;
  FCF4_calc(&target_speed_F4_FC, &target_speed_F4_FCMem, ai, ao);
  *o0=ao[0];
}
/*############################################################################*/
/*                       Function to release the memory                       */
/*                     which was allocated by xx-init().                      */
/*############################################################################*/


void target_speed_F4_free(void)
{
  FCF4_free(&target_speed_F4_FC, &target_speed_F4_FCMem);
}
