/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  MCURally                               */
/*      FILE         :  typedefine.h                           */
/*      DESCRIPTION  :  Aliases of Integer Type                */
/*      CPU SERIES   :  RX600                                  */
/*      CPU TYPE     :  RX62G                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                              
                                                                           
#ifndef _TYPDEFINE_H
#define _TYPDEFINE_H
                                                                           
                                                                            
/*********************************************************************
*
* Device     : RX
*
* File Name  : typedefine.h
*
* Abstract   : Aliases of Integer Type.
*
* History    : 1.00  (2009-08-07)
*
* NOTE       : THIS IS A TYPICAL EXAMPLE.
*
* Copyright (C) 2009 Renesas Electronics Corporation.
* and Renesas Solutions Corporation. All rights reserved.
*
*********************************************************************/


typedef unsigned char 	bool_t;

typedef signed char _SBYTE;
typedef unsigned char _UBYTE;
typedef signed short _SWORD;
typedef unsigned short _UWORD;
typedef signed int _SINT;
typedef unsigned int _UINT;
typedef signed long _SDWORD;
typedef unsigned long _UDWORD;
typedef signed long long _SQWORD;
typedef unsigned long long _UQWORD;

#endif
